import {useEffect,useRef,useState} from 'react';import * as Tabs from '@radix-ui/react-tabs';
import {Search,Copy,ChevronRight,Terminal,Globe,Image,Braces,LoaderCircle,CheckCircle2,XCircle,Clock,ZoomIn,ZoomOut,RotateCcw,SquareDashedMousePointer,Upload} from 'lucide-react';
import { runtimeSdk } from '../sdk/runtimeSdk';import {useStudio} from '../store';import {fieldChanges,flattenSteps} from '../model';import {Button} from './ui/button';import {Dialog} from './ui/dialog';
export async function copyValue(value:unknown){try{await navigator.clipboard.writeText(typeof value==='string'?value:JSON.stringify(value,null,2));runtimeSdk.toast('已複製。');}catch{runtimeSdk.toast('瀏覽器無法存取剪貼簿。',true);}}
function JsonBranch({name,value,level=0}:{name:string;value:unknown;level?:number}){const structured=value!==null&&typeof value==='object';return structured?<details className="json-branch" open={level===0}><summary><ChevronRight size={14}/><b>{name}</b><span className="muted">{Array.isArray(value)?`[${value.length}]`:`{${Object.keys(value as object).length}}`}</span><button aria-label={`複製 ${name}`} onClick={e=>{e.preventDefault();void copyValue(value);}}><Copy size={13}/></button></summary><div className="json-children">{Object.entries(value as object).map(([k,v])=><JsonBranch key={k} name={k} value={v} level={level+1}/>)}</div></details>:<div className="json-leaf"><b>{name}</b><code>{JSON.stringify(value)}</code><Button size="icon" variant="ghost" aria-label={`複製 ${name}`} onClick={()=>void copyValue(value)}><Copy size={13}/></Button></div>;}
function ScreenshotViewer(){const [src,setSrc]=useState('');const [open,setOpen]=useState(false);const [zoom,setZoom]=useState(1);const [mark,setMark]=useState(false);const [rect,setRect]=useState<{x:number;y:number;w:number;h:number}|null>(null);const start=useRef<{x:number;y:number}|null>(null);const imageWrap=useRef<HTMLDivElement>(null);
  useEffect(()=>()=>{if(src)URL.revokeObjectURL(src);},[src]);
  const coords=(e:React.PointerEvent)=>{const b=imageWrap.current!.getBoundingClientRect();return {x:Math.max(0,Math.min(100,(e.clientX-b.left)/b.width*100)),y:Math.max(0,Math.min(100,(e.clientY-b.top)/b.height*100))};};
  return <div className="screenshot-panel"><p>選取本機 Debug 截圖或已遮罩的診斷包截圖，檢查畫面與人工標記失敗位置。</p><label className="ui-button ui-secondary screenshot-upload"><Upload size={16}/>開啟本機截圖<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;setSrc(URL.createObjectURL(f));setOpen(true);setZoom(1);setRect(null);e.target.value='';}}/></label>{src&&<button className="screenshot-thumb" onClick={()=>setOpen(true)} aria-label="放大截圖"><img src={src} alt="本機 Debug 截圖"/></button>}<small>圖片僅在此瀏覽器顯示；紅框為人工標記。既有截圖遮罩仍由原診斷功能負責。</small><Dialog open={open} onOpenChange={setOpen} title="截圖檢查" description="使用縮放工具查看細節；可拖曳框選失敗位置。"><div className="image-tools"><Button size="sm" onClick={()=>setZoom(z=>Math.min(4,z+.25))}><ZoomIn size={15}/></Button><Button size="sm" onClick={()=>setZoom(z=>Math.max(.25,z-.25))}><ZoomOut size={15}/></Button><span className="mono">{Math.round(zoom*100)}%</span><Button size="sm" onClick={()=>{setZoom(1);setRect(null);}}><RotateCcw size={15}/>重設</Button><Button size="sm" variant={mark?'default':'secondary'} onClick={()=>setMark(v=>!v)}><SquareDashedMousePointer size={15}/>標記失敗位置</Button></div><div className="lightbox-scroll"><div ref={imageWrap} className={`lightbox-image ${mark?'mark-mode':''}`} style={{width:`${zoom*100}%`}} onPointerDown={e=>{if(!mark)return;start.current=coords(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!start.current||!mark)return;const p=coords(e),s=start.current;setRect({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)});}} onPointerUp={()=>{start.current=null;}}><img src={src} alt="Debug 截圖放大檢視" draggable={false}/>{rect&&<div className="failure-rect" style={{left:`${rect.x}%`,top:`${rect.y}%`,width:`${rect.w}%`,height:`${rect.h}%`}}/>}</div></div></Dialog></div>;
}
export function DebugInspector(){const {snapshot}=useStudio();const run=snapshot.state.currentRun;const events=snapshot.state.currentRunDebug?.events??[];const [tab,setTab]=useState('log');const [search,setSearch]=useState('');const [level,setLevel]=useState('all');
  const list=events.filter((e:any)=>tab==='console'?e.type==='console':tab==='network'?['request_failed','http_error'].includes(e.type):tab==='popup'?['page_opened','dialog','download_completed'].includes(e.type):!['console','http_error','request_failed'].includes(e.type)).filter((e:any)=>{const severity=e.level==='warning'?'warn':e.level??(/fail|error/.test(e.type)?'error':'info');return (level==='all'||severity===level||level==='info'&&severity==='log')&&JSON.stringify(e).toLowerCase().includes(search.toLowerCase());});
  const tabs=[['log','事件',Terminal],['console','Console',Terminal],['network','Network',Globe],['popup','Popup / Download',Globe],['variables','變數',Braces],['screenshot','截圖',Image]] as const;
  return <section className="inspector-panel"><Tabs.Root value={tab} onValueChange={setTab}><Tabs.List className="inspector-tabs">{tabs.map(([id,label,Icon])=><Tabs.Trigger key={id} value={id}><Icon size={14}/>{label}</Tabs.Trigger>)}</Tabs.List>{!['variables','screenshot'].includes(tab)&&<div className="inspector-filter"><Search size={15}/><input aria-label="搜尋日誌" value={search} placeholder="搜尋訊息、網址、步驟…" onChange={e=>setSearch(e.target.value)}/><select aria-label="日誌等級" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">全部等級</option><option value="error">Error</option><option value="warn">Warn</option><option value="info">Info</option></select><Button size="icon" variant="ghost" aria-label="複製目前日誌" onClick={()=>void copyValue(list)}><Copy size={15}/></Button></div>}{tabs.map(([id])=><Tabs.Content key={id} value={id} className="inspector-content">{id==='variables'?<JsonBranch name="流程變數" value={snapshot.state.currentRunDebug?.variables??run?.variables??{}}/>:id==='screenshot'?<ScreenshotViewer/>:<>{id==='network'&&<div className="inspector-note">沿用原有紀錄：失敗請求及 HTTP 4xx / 5xx 回應。</div>}{list.length?list.map((e:any,i:number)=><article className={`event-line ${e.level??e.type}`} key={i}><time>{e.at?new Date(e.at).toLocaleTimeString('zh-TW',{hour12:false}):'—'}</time><span className="event-type">{e.type==='console'?e.level:e.type}</span><code>{e.text??e.message??e.failure??e.name??e.stepId??''}{e.url&&<span className="event-url">{e.method?`${e.method} `:''}{e.status?`${e.status} `:''}{e.url}</span>}{e.filePath&&<span className="event-url">{e.filePath}</span>}</code></article>):events.length?<div className="inspector-empty">沒有符合篩選的事件。</div>:run?<pre className="event-log-fallback">{runtimeSdk.debugText(id)}</pre>:<div className="inspector-empty">執行流程後顯示即時紀錄。</div>}</>}</Tabs.Content>)}</Tabs.Root></section>;
}
export function DebugWorkbench(){const run=useStudio(s=>s.snapshot.state.currentRun);return <div className="debug-workbench" data-empty={!run?.steps?.length}><aside className="execution-timeline"><div className="inspector-heading"><b>步驟時序</b><span className="pill">{run?.steps?.length??0} 次嘗試</span></div>{run?.steps?.length?run.steps.map((s:any,i:number)=><article key={i} className={`timeline-attempt ${s.status}`}><span className="timeline-dot">{s.status==='running'?<LoaderCircle size={16} className="animate-spin"/>:s.status==='completed'?<CheckCircle2 size={16}/>:s.status==='failed'?<XCircle size={16}/>:<Clock size={16}/>}</span><div><b>{s.name}</b><small>{s.status==='running'?'執行中':s.status==='completed'?'已完成':s.status==='failed'?'失敗':'等待 / 略過'} · 第 {s.attempt??1} 次嘗試</small>{s.message&&<p>{s.message}</p>}</div><span className="mono duration">{s.durationMs!=null?`${(s.durationMs/1000).toFixed(2)}s`:'—'}</span></article>):<div className="modern-empty">等待流程開始執行。</div>}</aside><DebugInspector/></div>;}
export function DiagnosticsDiff(){const {snapshot}=useStudio();const analysis=snapshot.state.debugAIAnalysis;const run=snapshot.state.currentRun;if(!analysis||!run)return null;const id=analysis.failedStepId??[...(run.steps??[])].reverse().find(s=>s.status==='failed')?.stepId;const step=flattenSteps(snapshot.state.project?.steps??[]).find(s=>s.step.id===id)?.step;const changes=fieldChanges(step,step?{...step,...analysis.proposedPatch}:undefined);return <div className="diagnostics-diff"><span className={`confidence ${analysis.confidence}`}>信心度 · {({high:'高',medium:'中',low:'低'} as Record<string,string>)[analysis.confidence]??'未提供'}</span><h3>候選設定差異</h3>{changes.length?changes.map(c=><div className="field-diff" key={c.key}><b>{c.key}</b><div className="diff-before"><span>−</span><code>{JSON.stringify(c.before,null,2)??'未設定'}</code></div><div className="diff-after"><span>+</span><code>{JSON.stringify(c.after,null,2)??'未設定'}</code></div></div>):<p>沒有候選設定變更。</p>}</div>;}
