# Run only in a separate test copy of the application; creates ui-verification test data.
import json,os,time,zipfile,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
out=Path(os.environ.get('UI_TEST_ARTIFACTS','verification/ui-artifacts'));out.mkdir(exist_ok=True)
checks=[]
def check(name,condition=True):
 assert condition,name
 checks.append(name);print('PASS',name,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,executable_path=os.environ.get('TEST_CHROMIUM'),args=['--no-sandbox','--disable-dev-shm-usage'])
 context=browser.new_context(viewport={'width':1440,'height':1050},permissions=['clipboard-read','clipboard-write'])
 page=context.new_page();errors=[];external=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:external.append(r.url) if not r.url.startswith(('http://127.0.0.1:4175','blob:','data:')) else None)
 def step(id,kind='wait',**args):return {'id':id,'name':id,'kind':kind,'enabled':True,'value':'1','waitAfter':{'kind':'timeout','timeoutMs':1},**args}
 parameters=[{'id':'y','name':'year','label':'年度','type':'select','required':True,'defaultValue':'114','options':['114','115']},{'id':'s','name':'stage','label':'階段','type':'select','required':True,'defaultValue':'1','options':['1','2','3'],'dependsOn':'year','dependentOptions':{'114':['1'],'115':['2','3']}},{'id':'n','name':'amount','label':'金額','type':'number','required':True,'defaultValue':'0'}]
 tree=[step('start','navigate',url='http://127.0.0.1:4175/'),step('branch','condition',condition={'source':'parameter','name':'year','operator':'equals','value':'115'},thenSteps=[step('yes')],elseSteps=[step('no')]),step('loop','loop',loopVariable='item',loopValues=['1'],steps=[step('inside')]),step('end')]
 project=page.request.post('http://127.0.0.1:4175/api/studio/projects',data={'id':'ui-verification','name':'UI 驗證專案','targetUrl':'http://127.0.0.1:4175/','allowedDomains':['127.0.0.1'],'adapter':'generic','parameters':parameters,'steps':tree,'browser':{'channel':'chromium','headless':True}}).json()['project']
 page.goto('http://127.0.0.1:4175');page.wait_for_load_state('networkidle');page.screenshot(path=str(out/'dashboard.png'),full_page=True);page.wait_for_function("window.studioBridge && document.documentElement.classList.contains('modern-active')")
 check('React boots and keeps original controller available')
 page.evaluate("id=>window.studioBridge.loadProject(id)",project['id']);page.evaluate("window.studioBridge.navigate('designer')")
 expect(page.locator('.modern-list .modern-step')).to_have_count(7)
 expect(page.locator('.modern-list .step-drag')).to_have_count(0)
 check('Nested list includes both branches and loop contents')
 # Single click selects without opening settings; double-click opens the sheet.
 palette=page.locator('.palette-pane');expect(palette).to_have_class(re.compile('is-collapsed'))
 expect(page.locator('#stepPalette')).to_be_hidden();palette.hover();expect(page.locator('#stepPalette')).to_be_visible()
 check('Collapsed palette reveals all actions on hover')
 page.get_by_role('button',name='展開動作元件').click();expect(page.locator('#stepPalette')).to_be_visible()
 page.get_by_role('button',name='收合動作元件').click();expect(page.locator('#stepPalette')).to_be_hidden()
 page.mouse.move(700,100);palette.hover();expect(page.locator('#stepPalette')).to_be_visible()
 check('Collapse button works while hovered and the palette reopens on later hover')
 page.get_by_role('button',name='展開動作元件').click()
 page.locator('[data-modern-step="yes"]').click()
 expect(page.locator('[data-modern-step="yes"]')).to_have_class(re.compile('selected'))
 expect(page.get_by_role('dialog')).to_have_count(0)
 check('Single click selects a step without opening settings')
 page.locator('[data-modern-step="yes"]').dblclick()
 expect(page.get_by_role('dialog')).to_be_visible();expect(page.locator('#stepName')).to_have_value('yes')
 check('Double-click opens the Property Sheet for selected nested step')
 page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click()
 page.locator('[data-modern-step="no"]').click()
 expect(page.locator('[data-modern-step="no"]')).to_have_class(re.compile('selected'))
 expect(page.get_by_role('dialog')).to_have_count(0)
 page.locator('[data-modern-step="yes"]').dblclick();expect(page.get_by_role('dialog')).to_be_visible()
 check('Selecting another step stays closed after the snapshot update')
 page.screenshot(path=str(out/'property-debug.png'),full_page=True)
 page.get_by_role('dialog').locator('summary').filter(has_text='等待、重試與驗證').click();page.locator('#modernRetryCount').fill('2')
 page.locator('#stepName').fill('條件成立步驟');page.locator('#saveStepButton').click();expect(page.locator('#stepName')).to_have_value('條件成立步驟')
 page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click()
 check('Nested step edits use original apply handler')
 check('Retry setting saves to original step schema',page.evaluate("window.studioBridge.selected().retryCount")==2)
 page.locator('[data-modern-step="yes"]').hover();page.locator('[data-modern-step="yes"]').get_by_role('button',name='複製步驟',exact=True).click()
 expect(page.locator('.modern-list .modern-step')).to_have_count(8)
 if page.get_by_role('dialog').count():page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click()
 check('Duplicate renews nested step IDs')
 page.get_by_role('button',name='視覺畫布',exact=True).click();expect(page.locator('.react-flow')).to_be_visible();expect(page.locator('.condition-diamond')).to_have_count(1)
 check('React Flow renders diamond, branches and loop')
 page.locator('.react-flow__node[data-id="branch"] .condition-diamond').click()
 expect(page.locator('.react-flow__node[data-id="branch"] .flow-step')).to_have_class(re.compile('selected'))
 expect(page.get_by_role('dialog')).to_have_count(0)
 page.locator('.react-flow__node[data-id="branch"] .condition-diamond').dblclick()
 expect(page.get_by_role('dialog')).to_be_visible()
 page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click()
 check('Canvas steps select on click and open settings on double-click')
 page.screenshot(path=str(out/'designer-canvas.png'),full_page=True)
 inserts=page.locator('.flow-edge-label[data-owner="root"][data-index="0"]').filter(has=page.get_by_role('button',name='在此插入動作'))
 inserts.first.get_by_role('button',name='在此插入動作').click();expect(page.get_by_role('dialog')).to_be_visible();page.get_by_role('dialog').get_by_role('button',name='等待',exact=True).click()
 if page.get_by_role('dialog').count():page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click()
 check('Canvas edge inserts a step through the tree adapter',page.evaluate("window.studioBridge.snapshot().state.project.steps.length")==5)
 page.get_by_role('button',name='階層清單',exact=True).click()
 page.keyboard.press('Control+k');expect(page.locator('[cmdk-input]')).to_be_visible();page.locator('[cmdk-input]').fill('批次任務');page.keyboard.press('Enter');expect(page.locator('#modern-batch')).to_be_visible()
 check('Ctrl+K searches and navigates')
 page.get_by_role('button',name='新增一列',exact=True).click();page.locator('[data-grid-row="0"][data-grid-col="0"]').focus()
 page.locator('[data-grid-row="0"][data-grid-col="0"]').dispatch_event('paste',{'clipboardData':None}) if False else None
 page.evaluate("""()=>{const cell=document.querySelector('[data-grid-row="0"][data-grid-col="0"]');const dt=new DataTransfer();dt.setData('text/plain','115\\t2\\t42\\n114\\t1\\t7');cell.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true}));}""")
 expect(page.locator('[data-grid-row="1"][data-grid-col="2"]')).to_contain_text('7')
 check('Excel multirow paste creates rows and preserves dependent choices')
 before=page.evaluate('JSON.stringify(window.studioBridge.snapshot().state.batchRows)')
 page.evaluate("""()=>{const cell=document.querySelector('[data-grid-row="0"][data-grid-col="0"]');const dt=new DataTransfer();dt.setData('text/plain','115\\t1\\t50');cell.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true}));}""")
 expect(page.locator('.grid-errors')).to_be_visible();check('Invalid child option rejects the entire paste',page.evaluate('JSON.stringify(window.studioBridge.snapshot().state.batchRows)')==before)
 page.locator('.grid-errors').get_by_role('button',name='關閉').click()
 cell=page.locator('[data-grid-row="0"][data-grid-col="2"]');cell.dblclick();cell.locator('input').fill('88');cell.locator('input').press('Enter');expect(cell).to_contain_text('88')
 check('Cell double-click editing commits through original batch state')
 page.locator('[data-grid-row="0"][data-grid-col="0"]').focus();page.keyboard.press('ArrowRight');page.wait_for_function("document.activeElement.dataset.gridCol==='1'");check('Grid arrow navigation',page.evaluate("document.activeElement.dataset.gridCol")== '1')
 page.get_by_role('button',name='選取前 10 筆').click();page.get_by_label('批次修改欄位').select_option('amount');page.get_by_label('批次修改值').fill('99');page.get_by_role('button',name='套用至選取列').click();check('Bulk edit touches selected rows',page.evaluate("window.studioBridge.snapshot().state.batchRows.every(r=>r.parameters.amount==='99')"))
 page.screenshot(path=str(out/'batch-grid.png'),full_page=True)
 page.evaluate("""()=>{const s=window.studioBridge.snapshot().state;s.batchRows=Array.from({length:1000},(_,i)=>({id:'large-'+i,enabled:true,parameters:{year:'115',stage:'2',amount:String(i)}}));window.studioBridge.setBatchRows(s.batchRows);}""")
 check('Batch virtualization renders bounded DOM',page.locator('.modern-data-grid tbody tr').count()<30)
 # Return to designer and verify saved JSON and local Monaco worker requests.
 page.evaluate("window.studioBridge.navigate('designer')");page.locator('[data-modern-step="start"]').click();page.wait_for_function("document.querySelector('.monaco-editor')")
 check('Monaco selector editor loads local assets')
 page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click();page.evaluate("window.studioBridge.save()")
 persisted=page.request.get('http://127.0.0.1:4175/api/studio/projects/ui-verification').json()['project'];check('Saving retains nested structure and edits',persisted['steps'][2]['thenSteps'][0]['name']=='條件成立步驟')
 page.evaluate("window.studioBridge.navigate('publish')")
 with page.expect_download() as download:page.locator('#exportButton').click()
 path=out/'export-verification.zip';download.value.save_as(path)
 with zipfile.ZipFile(path) as z:
  check('Export ZIP retains TypeScript and portable workflow',any(n.endswith('.ts') for n in z.namelist()) and any(n.endswith('workflow.json') for n in z.namelist()))
 page.evaluate("""()=>{const s=window.studioBridge.snapshot().state;s.currentRun={id:'ui-debug',projectId:s.project.id,status:'failed',mode:'full',startedAt:new Date().toISOString(),totalSteps:1,completedSteps:0,downloads:[],debugDir:'test',errorMessage:'測試錯誤',steps:[{stepId:'start',name:'開啟頁面',status:'failed',kind:'navigate',attempt:2,durationMs:1200}]};s.currentRunDebug={events:[{type:'console',level:'error',text:'驗證錯誤',at:new Date().toISOString()},{type:'http_error',status:403,url:'http://localhost/report',at:new Date().toISOString()}],variables:{report:{year:115,total:42}},downloads:[]};s.debugAIAnalysis={summary:'測試分析',rootCause:'範例',confidence:'high',failedStepId:'start',proposedPatch:{timeoutMs:60000},evidence:['範例'],suggestions:['範例']};s.debugAIAnalysisRunId='ui-debug';renderRun(s.currentRun);window.studioBridge.navigate('test');}""")
 expect(page.locator('.timeline-attempt')).to_have_count(1);expect(page.locator('.duration')).to_have_text('1.20s');check('Debug timeline shows actual elapsed time and attempts')
 page.get_by_role('tab',name='Console',exact=True).click();page.get_by_label('搜尋日誌').fill('驗證');expect(page.locator('.event-line')).to_have_count(1);check('Console search filters original event data')
 page.get_by_role('tab',name='變數',exact=True).click();expect(page.locator('.json-branch')).to_have_count(2);check('Variables use collapsible JSON tree')
 expect(page.locator('.confidence.high')).to_be_visible();expect(page.locator('.diagnostics-diff .field-diff')).to_have_count(1);check('AI diagnosis presents confidence and before/after patch')
 page.screenshot(path=str(out/'debug-workbench.png'),full_page=True)
 # Local screenshot viewer never calls upload APIs.
 page.get_by_role('tab',name='截圖',exact=True).click();page.locator('.screenshot-upload input').set_input_files(str(out/'dashboard.png'));expect(page.get_by_role('dialog')).to_be_visible();page.get_by_role('dialog').get_by_role('button',name='標記失敗位置').click();img=page.locator('.lightbox-image').bounding_box();page.mouse.move(img['x']+20,img['y']+20);page.mouse.down();page.mouse.move(img['x']+100,img['y']+100);page.mouse.up();expect(page.locator('.failure-rect')).to_be_visible();page.get_by_role('dialog').get_by_role('button',name='關閉',exact=True).click();check('Local screenshot lightbox zoom and red-box annotation')
 page.evaluate("""()=>{const s=window.studioBridge.snapshot().state;const d={name:'AI 測試草稿',description:'本機 UI 測試',targetUrl:s.project.targetUrl,allowedDomains:s.project.allowedDomains,adapter:'generic',parameters:s.project.parameters,steps:[{id:'ai-a',name:'等待',kind:'wait',enabled:true,value:'1'}]};s.aiWorkflowDraft=d;s.aiWorkflowValidation={valid:true,errors:[],warnings:[]};s.aiWorkflowConversation=[{role:'user',content:'請修改等待時間'},{role:'assistant',content:'已準備候選修改，請查看差異。'}];s.aiWorkflowPendingRevision={draft:{...d,steps:[{...d.steps[0],value:'2000'},{id:'ai-b',name:'下載',kind:'download',enabled:true}]},validation:{valid:true,errors:[],warnings:[]},diff:{changed:true,summary:['等待時間已修改'],steps:[{id:'ai-a',type:'modified'},{id:'ai-b',type:'added'}],parameters:{added:[],modified:[],removed:[]}}};window.studioBridge.navigate('aiWorkflow');renderAIWorkflowAssistant();}""")
 expect(page.locator('.modern-ai-diff .diff-step.modified')).to_have_count(1);expect(page.locator('.modern-ai-diff .diff-step.added')).to_have_count(1);expect(page.locator('.ai-floating-bar')).to_be_visible();check('AI chat and field-level candidate diff')
 page.screenshot(path=str(out/'ai-diff.png'),full_page=True)
 page.locator('.ai-floating-bar').get_by_role('button',name='僅更新草稿',exact=True).click();page.wait_for_function('!window.studioBridge.snapshot().state.aiWorkflowPendingRevision');check('AI draft accept uses existing validation/history action')
 page.locator('.ai-floating-bar').get_by_role('button',name='復原上一版',exact=True).click();page.wait_for_function("window.studioBridge.snapshot().state.aiWorkflowDraft.steps[0].value==='1'");check('AI undo restores previous draft without provider call')
 # View navigation and responsive surfaces.
 for view in ['dashboard','workstation','parameters','test','batch','runs','publish','settings','help','report','developer']:
  page.evaluate('v=>window.studioBridge.navigate(v)',view);page.wait_for_timeout(80);check('Navigate '+view,page.locator('#'+view+'View').is_visible())
 page.get_by_role('button',name='切換深淺色',exact=True).click();check('Theme switch',page.evaluate('document.documentElement.dataset.theme')=='dark');page.evaluate("window.studioBridge.navigate('dashboard')");page.screenshot(path=str(out/'dashboard-dark.png'),full_page=True)
 page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(out/'mobile.png'),full_page=True);check('Mobile layout avoids body overflow',page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+1'))
 check('Removed classic interface returns not found',page.request.get('http://127.0.0.1:4175/classic/').status==404)
 check('No JavaScript page errors',not errors);check('No external frontend resource requests',not external)
 (out/'results.json').write_text(json.dumps({'checks':checks,'errors':errors,'external_requests':external},ensure_ascii=False,indent=2))
 browser.close()
